name: Prod Deployment
env:
    RESOURCE_GROUP: rg-aip   

on:
  pull_request_review_comment:
    types: [created]
  push:
    branches:
      - development
    paths:
      - ".github/workflows/DeployARM_Dev.yml" 

jobs:
  deploy-arm-template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Deploy to Prod
        shell: bash      
        run: |
           echo "Production Deployment in progress !"
